### ISSUE TITLE
Pull 311 data filtered by date, rather than entries limit

### ISSUE THREAD

**Issue by phcantis** [mebauer/elsa-flooding-nyc-311#3]
In the "query data for street flooding complaints" section, service requests are being downloaded fully (since 2010, I assume), with a limit to the maximum number of rows. 

Since in this project you are interest in a specific date, it would be more efficient to filter the data by date before downloading it. That way (especially now that you have done the sanity checks) you can save yourself from a) a longer download of heavier data and b) having to filter it later. 

Im guessing this would require to convert your query into sth like:

```
query = """
SELECT 
    *
WHERE 
    created_date BETWEEN  '2021-07-07T00:00:00.000' AND  '2021-07-13T00:00:00.000'

    AND

    descriptor = 'Street Flooding (SJ)'
"""
```

Doing this (if I am right), the query will first filter the whole dataset by date, making it much smaller and manageable, to then isolate the descriptor of interest.

**Comment by mebauer** [comment]
Thanks for the feedback! You're certainly right that my query is an inefficient way to retrieve specific dates, but for this purpose, I wanted to use it as sort of a tutorial/guide in how to query the data. And since the data (for this particular query) is quite small, there's no risk of potentially reading in a large file.  However, I would definitely recommend your suggestion for a much larger and complex query (e.g. all sewer complaints, regardless of descriptor).
